[phases.setup]
nixPkgs = ["python311", "nodejs-18_x", "yarn"]
aptPkgs = []

[phases.install]
cmds = [
  "cd backend && pip install -r requirements.txt",
  "cd frontend && yarn install"
]

[phases.build]
cmds = [
  "cd frontend && yarn build"
]

